version: '2'


volumes:
  puppetdb:

services:
  puppet:
    build:
      context: image/puppet-server
    hostname: puppet
    container_name: puppet
    #environment:
    #  - PUPPETSERVER_HOSTNAME=192.168.122.169
    ports:
      - 8140:8140

  puppetdb:
    image: puppet/puppetdb:5.2.4
    hostname: puppetdb
    container_name: puppetdb
    environment:
      - PUPPERWARE_ANALYTICS_ENABLED=false
      - CERTNAME=puppetdb
      - DNS_ALT_NAMES=false
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETSERVER_PORT=8140
      - PUPPETDB_POSTGRES_HOSTNAME=puppet-postgres
      - PUPPETDB_USER=puppetdb
      - PUPPETDB_PASSWORD=puppetdb
      - PUPPETDB_DATABASE_CONNECTION=//puppet-postgres:5432/puppetdb
    depends_on:
      - puppet
    volumes:
      - puppetdb:/etc/puppetlabs/puppetdb:rw
    entrypoint: /sbin/init

  puppet-postgres:
    image: postgres:9.6
    hostname: puppet-postgres
    container_name: puppet-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb

  puppetboard:
    image: ghcr.io/voxpupuli/puppetboard:3.4.0rc2
    environment:
      - PUPPETDB_HOST=puppetdb
      - PUPPETDB_PORT=8081
      - PUPPETDB_SSL_VERIFY=/etc/puppetlabs/puppetdb/ssl/ca.pem
      - PUPPETDB_KEY=/etc/puppetlabs/puppetdb/ssl/private.pem
      - PUPPETDB_CERT=/etc/puppetlabs/puppetdb/ssl/public.pem
    volumes:
      - puppetdb:/etc/puppetlabs/puppetdb:rw
    ports:
      - "7777:80"

  puppet-slave1:
    build:
      context: image/puppet-agent-ubuntu
    hostname: agent1.example.com

