#!/usr/bin/env bash

echo "======> create database, create default user: puppetdb pwd:bbb "
sudo -u postgres psql -c "create database testdb;"
sudo -u postgres psql -c "create user puppetdb;"
sudo -u postgres psql -c "alter user puppetdb with encrypted password 'bbb';"
sudo -u postgres psql -c "grant all privileges on database testdb to puppetdb;"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to puppetdb;"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to puppetdb;"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to puppetdb;"