#!/usr/bin/env bash

echo "======> overwrite postgres config "
sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /var/lib/pgsql/data/postgresql.conf
sed -i '/# IPv4 local connections:/a host    all             all             0.0.0.0/0            md5' /var/lib/pgsql/data/pg_hba.conf